import SwiftUI
import SwiftData
import UIKit

struct ExerciseDetailView: View {
    @Environment(\.modelContext) private var context
    @EnvironmentObject private var badgeUnlockCoordinator: BadgeUnlockCoordinator
    @Bindable var entry: WorkoutEntry
    var parentWorkoutHint: WorkoutDay? = nil

    @Query(sort: \WorkoutDay.date, order: .reverse) private var workouts: [WorkoutDay]

    @State private var completionPulse = false

    var body: some View {
        let isTest = entry.exercise.isTestExercise
        let progressSnapshot = ExerciseProgressCalculator.snapshot(for: entry, in: workouts)
        let basicStats = ExerciseProgressCalculator.basicStats(for: entry, in: workouts)
        let testSnapshot = isTest ? TestResultCalculator.snapshot(for: entry, in: workouts) : nil

        List {
            if !entry.exercise.notes.isEmpty {
                Section("Cómo se hace") {
                    Text(entry.exercise.notes)
                        .foregroundStyle(.secondary)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .xkalaCard()
                        .listRowSeparator(.hidden)
                        .listRowBackground(Color.clear)
                        .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
                }
            }

            Section("Estado") {
                VStack(spacing: 12) {
                    Toggle(
                        "Ejercicio completado",
                        isOn: Binding(
                            get: { entry.isDone },
                            set: { newValue in
                                withAnimation(.spring(response: 0.28, dampingFraction: 0.75)) {
                                    entry.isDone = newValue
                                    if newValue { triggerCompletionFeedback() }
                                    parentWorkout?.syncAutoGeneratedSessionNameIfNeeded()
                                    try? context.save()
                                }
                            }
                        )
                    )

                    if entry.isDone {
                        HStack(spacing: 10) {
                            Image(systemName: "checkmark.circle.fill")
                                .font(.system(size: 20))
                                .foregroundStyle(XkalaTheme.mint)
                            Text("Completado")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                            Spacer()
                        }
                        .scaleEffect(completionPulse ? 1.03 : 1.0)
                        .opacity(completionPulse ? 1.0 : 0.92)
                        .onAppear {
                            completionPulse = true
                            DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) {
                                withAnimation(.easeOut(duration: 0.25)) {
                                    completionPulse = false
                                }
                            }
                        }
                    }

                    if entry.usesBlockEditor || entry.usesTraverseEditor {
                        Toggle(
                            "Completado con éxito",
                            isOn: Binding(
                                get: { entry.climbSuccess ?? false },
                                set: { newValue in
                                    entry.climbSuccess = newValue
                                    try? context.save()
                                    evaluateBadgesAfterEntryChange(reason: .climbSuccess)
                                }
                            )
                        )
                    }

                    if !entry.usesBlockEditor && !entry.usesTraverseEditor {
                        IntControlRow(
                            title: "Intensidad",
                            value: $entry.intensity,
                            range: 1...3,
                            step: 1
                        )
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .xkalaCard()
                .listRowSeparator(.hidden)
                .listRowBackground(Color.clear)
                .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
            }

            if isTest {
                Section {
                    HStack(spacing: 10) {
                        Image(systemName: "flag.checkered")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(XkalaTheme.mint)
                        Text("Esto es un test. Registra tus intentos válidos; Xkala tomará el mejor resultado.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .xkalaCard()
                    .listRowSeparator(.hidden)
                    .listRowBackground(Color.clear)
                    .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
                }
            }

            Section("Registro") {
                VStack(spacing: 12) {
                    if entry.usesBlockEditor {
                        BlockEntryEditorView(entry: entry)
                    } else if entry.usesTraverseEditor {
                        TraverseEntryEditorView(entry: entry)
                    } else if entry.usesIntermittentHangboardEditor {
                        IntermittentHangboardEditorView(
                            workSeconds: Binding(
                                get: { entry.sets.first?.seconds ?? 0 },
                                set: { newValue in applyIntermittentWorkSecondsToAll(newValue) }
                            ),
                            restSeconds: Binding(
                                get: { intermittentRestSeconds(from: entry.entryNotes) ?? 0 },
                                set: { newValue in
                                    entry.entryNotes = writingIntermittentRestSeconds(newValue, into: entry.entryNotes)
                                }
                            ),
                            rounds: Binding(
                                get: { entry.sets.first?.reps ?? 0 },
                                set: { newValue in applyIntermittentRoundsToAll(newValue) }
                            ),
                            cycles: Binding(
                                get: { entry.sets.count },
                                set: { newCount in resizeSets(to: newCount) }
                            ),
                            loadKg: Binding(
                                get: { entry.sets.first?.loadKg ?? 0 },
                                set: { newValue in applyLoadToAll(newValue) }
                            ),
                            loadAllowed: entry.exercise.loadAllowed
                        )
                    } else {
                        if entry.usesCircuitEditor {
                            IntControlRow(
                                title: "Nº vueltas",
                                value: Binding(
                                    get: { entry.sets.first?.reps ?? 0 },
                                    set: { newValue in
                                        ensureSingleSetForCircuit()
                                        entry.sets.first?.reps = newValue
                                        entry.sets.first?.seconds = nil
                                        entry.sets.first?.loadKg = nil
                                    }
                                ),
                                range: 0...20,
                                step: 1
                            )
                        } else {
                            IntControlRow(
                                title: "Series",
                                value: Binding(
                                    get: { entry.sets.count },
                                    set: { newCount in
                                        resizeSets(to: newCount)
                                    }
                                ),
                                range: 0...30,
                                step: 1
                            )

                            if entry.exercise.modeEnum == .reps {
                                IntControlRow(
                                    title: repsTitle,
                                    value: Binding(
                                        get: { entry.sets.first?.reps ?? 0 },
                                        set: { newValue in
                                            applyRepsToAll(newValue)
                                        }
                                    ),
                                    range: 0...200,
                                    step: 1
                                )
                            } else {
                                TimeControlRow(
                                    title: "Tiempo",
                                    seconds: Binding(
                                        get: { entry.sets.first?.seconds ?? 0 },
                                        set: { newValue in
                                            applySecondsToAll(newValue)
                                        }
                                    ),
                                    range: 0...3600,
                                    stepSeconds: 5
                                )
                            }

                            if entry.exercise.loadAllowed {
                                DoubleControlRow(
                                    title: "Carga",
                                    suffix: "kg",
                                    value: Binding(
                                        get: { entry.sets.first?.loadKg ?? 0 },
                                        set: { newValue in
                                            applyLoadToAll(newValue)
                                        }
                                    ),
                                    range: -50...150,
                                    step: 0.5,
                                    decimals: 1
                                )
                            }
                        }
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .xkalaCard()
                .listRowSeparator(.hidden)
                .listRowBackground(Color.clear)
                .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
            }

            Section("Estadísticas") {
                ExerciseBasicStatsSectionView(snapshot: basicStats)
            }

            if let testSnapshot {
                Section("Resultados del Test") {
                    ExerciseTestSectionView(exercise: entry.exercise, snapshot: testSnapshot)
                }
            } else {
                Section("Progreso") {
                    ExerciseProgressSectionView(snapshot: progressSnapshot)
                }
            }

        }
        .scrollContentBackground(.hidden)
        .listStyle(.plain)
        .xkalaScreenBackground(.calendar)
        .navigationTitle(entry.exercise.name)
        .toolbar {
            ToolbarItemGroup(placement: .keyboard) {
                Spacer()
                Button("OK") { hideKeyboard() }
            }
        }
        .onAppear {
            if !entry.sets.isEmpty {
                normalizeSetsToExerciseRules()
            }
        }
        .onChange(of: entry.isDone) { _, newValue in
            if newValue { triggerCompletionFeedback() }
            if newValue && (entry.usesBlockEditor || entry.usesTraverseEditor) {
                evaluateBadgesAfterEntryChange(reason: .climbSuccess)
            }
        }
        .onDisappear {
            evaluateBadgesAfterEntryChange(reason: .sessionChange)
        }
    }

    private var parentWorkout: WorkoutDay? {
        if let parentWorkoutHint { return parentWorkoutHint }
        return workouts.first { day in
            day.entries.contains { $0.persistentModelID == entry.persistentModelID }
        }
    }

    private func evaluateBadgesAfterEntryChange(reason: BadgeEvaluationTrigger.Reason) {
        BadgeEvaluationTrigger.evaluateBadgesAfterSessionChange(
            context: context,
            coordinator: badgeUnlockCoordinator,
            currentWorkout: parentWorkout,
            reason: reason
        )
    }

    // MARK: - Animación + Haptic

    private func triggerCompletionFeedback() {
        completionPulse = true
        let generator = UINotificationFeedbackGenerator()
        generator.notificationOccurred(.success)

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) {
            withAnimation(.easeOut(duration: 0.25)) {
                completionPulse = false
            }
        }
    }

    private func ensureSingleSetForCircuit() {
        if entry.sets.isEmpty {
            entry.sets.append(SetRecord.make(for: entry.exercise))
        }

        while entry.sets.count > 1 {
            if let last = entry.sets.last {
                context.delete(last)
                entry.sets.removeLast()
            } else {
                break
            }
        }

        entry.sets.first?.seconds = nil
        entry.sets.first?.loadKg = nil

        if entry.sets.first?.reps == nil {
            entry.sets.first?.reps = 0
        }
    }

    private func ensureSingleSetForClimb() {
        if entry.sets.isEmpty {
            entry.sets.append(SetRecord.make(for: entry.exercise))
        }

        while entry.sets.count > 1 {
            if let last = entry.sets.last {
                context.delete(last)
                entry.sets.removeLast()
            } else {
                break
            }
        }

        entry.sets.first?.seconds = nil
        entry.sets.first?.loadKg = nil
    }

    // MARK: - Texto

    private var repsTitle: String {
        let name = entry.exercise.name.lowercased()
        let cat = entry.exercise.exerciseCategoryKeyForSemantics
        if cat == "campus" || name.contains("campus") {
            return "Repeticiones"
        }
        return "Reps"
    }

    // MARK: - Bloques / Travesías editors

    private struct BlockEntryEditorView: View {
        @Bindable var entry: WorkoutEntry

        private var attemptsBinding: Binding<Int> {
            Binding(
                get: { entry.sets.first?.reps ?? 0 },
                set: { newValue in
                    if entry.sets.isEmpty { entry.sets.append(SetRecord.make(for: entry.exercise)) }
                    entry.sets.first?.reps = newValue
                    entry.sets.first?.seconds = nil
                    entry.sets.first?.loadKg = nil
                }
            )
        }

        private var identifierBinding: Binding<String> {
            Binding(
                get: { entry.climbIdentifier ?? "" },
                set: { newValue in
                    let trimmed = newValue.trimmingCharacters(in: .whitespacesAndNewlines)
                    entry.climbIdentifier = trimmed.isEmpty ? nil : trimmed
                }
            )
        }

        private let gradeOptions: [(String, Color)] = [
            ("green", .green),
            ("yellow", .yellow),
            ("orange", .orange),
            ("purple", .purple)
        ]

        var body: some View {
            VStack(spacing: 12) {
                TextField("Identificador", text: identifierBinding)
                    .textInputAutocapitalization(.words)
                    .autocorrectionDisabled(true)
                    .frame(maxWidth: .infinity, alignment: .leading)

                HStack(spacing: 14) {
                    ForEach(gradeOptions.indices, id: \.self) { idx in
                        let option = gradeOptions[idx]
                        let isSelected = entry.climbGradeColor == option.0
                        Button {
                            entry.climbGradeColor = option.0
                        } label: {
                            Circle()
                                .fill(option.1)
                                .frame(width: 22, height: 22)
                                .overlay {
                                    if isSelected {
                                        Circle().stroke(Color.primary, lineWidth: 2)
                                    }
                                }
                        }
                        .buttonStyle(.plain)
                    }
                }

                IntControlRow(
                    title: "Intentos",
                    value: attemptsBinding,
                    range: 0...200,
                    step: 1
                )
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private struct TraverseEntryEditorView: View {
        @Bindable var entry: WorkoutEntry

        private var attemptsBinding: Binding<Int> {
            Binding(
                get: { entry.sets.first?.reps ?? 0 },
                set: { newValue in
                    if entry.sets.isEmpty { entry.sets.append(SetRecord.make(for: entry.exercise)) }
                    entry.sets.first?.reps = newValue
                    entry.sets.first?.seconds = nil
                    entry.sets.first?.loadKg = nil
                }
            )
        }

        private var identifierBinding: Binding<String> {
            Binding(
                get: { entry.climbIdentifier ?? "" },
                set: { newValue in
                    let upper = newValue.uppercased()
                    let firstLetter = upper.unicodeScalars.first(where: { scalar in
                        let v = scalar.value
                        return v >= 65 && v <= 90 // A-Z
                    })

                    if let firstLetter {
                        entry.climbIdentifier = String(UnicodeScalar(firstLetter.value)!)
                    } else {
                        entry.climbIdentifier = nil
                    }
                }
            )
        }

        var body: some View {
            VStack(spacing: 12) {
                TextField("Letra", text: identifierBinding)
                    .keyboardType(.alphabet)
                    .autocorrectionDisabled(true)
                    .textInputAutocapitalization(.characters)
                    .frame(maxWidth: .infinity, alignment: .leading)

                IntControlRow(
                    title: "Intentos",
                    value: attemptsBinding,
                    range: 0...200,
                    step: 1
                )
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private struct IntermittentHangboardEditorView: View {
        @Binding var workSeconds: Int
        @Binding var restSeconds: Int
        @Binding var rounds: Int
        @Binding var cycles: Int
        @Binding var loadKg: Double
        let loadAllowed: Bool

        var body: some View {
            VStack(spacing: 12) {
                TimeControlRow(
                    title: "Tiempo ejercicio",
                    seconds: $workSeconds,
                    range: 0...600,
                    stepSeconds: 1
                )

                TimeControlRow(
                    title: "Tiempo descanso",
                    seconds: $restSeconds,
                    range: 0...600,
                    stepSeconds: 1
                )

                IntControlRow(
                    title: "Nº rondas",
                    value: $rounds,
                    range: 0...50,
                    step: 1
                )

                IntControlRow(
                    title: "Nº ciclos",
                    value: $cycles,
                    range: 0...30,
                    step: 1
                )

                if loadAllowed {
                    DoubleControlRow(
                        title: "Carga",
                        suffix: "kg",
                        value: $loadKg,
                        range: -50...150,
                        step: 0.5,
                        decimals: 1
                    )
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    // MARK: - Lógica de sets (uniforme)

    private func ensureSetForMetricEdit() {
        guard entry.sets.isEmpty else { return }
        entry.sets.append(SetRecord.make(for: entry.exercise))
        normalizeSetsToExerciseRules()
    }

    private func resizeSets(to targetCount: Int) {
        let safeTarget = max(0, targetCount)
        let current = entry.sets.count
        guard safeTarget != current else { return }

        if safeTarget == 0 {
            for set in entry.sets {
                context.delete(set)
            }
            entry.sets.removeAll()
            return
        }

        if safeTarget > current {
            let extra = safeTarget - current
            for _ in 0..<extra {
                entry.sets.append(SetRecord.make(for: entry.exercise))
            }
        } else {
            let removeCount = current - safeTarget
            for _ in 0..<removeCount {
                if let last = entry.sets.last {
                    context.delete(last)
                    entry.sets.removeLast()
                }
            }
        }

        normalizeSetsToExerciseRules()
    }

    private func applyRepsToAll(_ reps: Int) {
        ensureSetForMetricEdit()
        for s in entry.sets {
            s.reps = reps
            s.seconds = nil
        }
        if !entry.exercise.loadAllowed {
            for s in entry.sets { s.loadKg = nil }
        }
    }

    private func applySecondsToAll(_ seconds: Int) {
        ensureSetForMetricEdit()
        for s in entry.sets {
            s.seconds = seconds
            if !entry.exercise.isIntermittentHangboardExercise {
                s.reps = nil
            }
        }
        if !entry.exercise.loadAllowed {
            for s in entry.sets { s.loadKg = nil }
        }
    }

    private func applyIntermittentWorkSecondsToAll(_ seconds: Int) {
        ensureSetForMetricEdit()
        for s in entry.sets {
            s.seconds = max(0, seconds)
        }
    }

    private func applyIntermittentRoundsToAll(_ rounds: Int) {
        ensureSetForMetricEdit()
        for s in entry.sets {
            s.reps = max(0, rounds)
        }
    }

    private func applyLoadToAll(_ load: Double) {
        ensureSetForMetricEdit()
        guard entry.exercise.loadAllowed else {
            for s in entry.sets { s.loadKg = nil }
            return
        }
        for s in entry.sets {
            s.loadKg = load
        }
    }

    private func normalizeSetsToExerciseRules() {
        guard !entry.sets.isEmpty else { return }

        if entry.exercise.isIntermittentHangboardExercise {
            for s in entry.sets {
                if s.seconds == nil { s.seconds = 0 }
                if s.reps == nil { s.reps = 0 }
                if entry.exercise.loadAllowed, s.loadKg == nil { s.loadKg = 0 }
            }
            if !entry.exercise.loadAllowed {
                for s in entry.sets { s.loadKg = nil }
            }
            return
        }

        if entry.exercise.modeEnum == .reps {
            for s in entry.sets { s.seconds = nil }
        } else {
            for s in entry.sets { s.reps = nil }
        }

        if !entry.exercise.loadAllowed {
            for s in entry.sets { s.loadKg = nil }
        }
    }

    private func intermittentRestSeconds(from notes: String) -> Int? {
        let pattern = #"\[intermittent_rest_seconds=(\d+)\]"#
        guard
            let regex = try? NSRegularExpression(pattern: pattern),
            let match = regex.firstMatch(in: notes, range: NSRange(notes.startIndex..., in: notes)),
            match.numberOfRanges > 1,
            let valueRange = Range(match.range(at: 1), in: notes)
        else {
            return nil
        }
        return Int(notes[valueRange])
    }

    private func writingIntermittentRestSeconds(_ seconds: Int, into notes: String) -> String {
        let safeValue = max(0, seconds)
        let token = "[intermittent_rest_seconds=\(safeValue)]"
        let pattern = #"\[intermittent_rest_seconds=\d+\]"#

        if let range = notes.range(of: pattern, options: .regularExpression) {
            var updated = notes
            updated.replaceSubrange(range, with: token)
            return updated
        }

        let trimmed = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty {
            return token
        }
        return "\(notes)\n\(token)"
    }

    // MARK: - Keyboard

    private func hideKeyboard() {
        UIApplication.shared.sendAction(
            #selector(UIResponder.resignFirstResponder),
            to: nil,
            from: nil,
            for: nil
        )
    }
}

// MARK: - Controles

private struct IntControlRow: View {
    let title: String
    @Binding var value: Int
    let range: ClosedRange<Int>
    let step: Int

    @State private var text: String = ""
    @FocusState private var focused: Bool

    var body: some View {
        HStack(spacing: 12) {
            Text(title)
            Spacer()

            EditableControlPill(
                text: Binding(
                    get: { text.isEmpty ? "\(value)" : text },
                    set: { text = $0 }
                ),
                suffix: nil,
                keyboard: .numberPad,
                canDecrement: value - step >= range.lowerBound,
                canIncrement: value + step <= range.upperBound,
                decrement: { value = max(value - step, range.lowerBound) },
                increment: { value = min(value + step, range.upperBound) },
                onCommit: {
                    let digits = text.filter { $0.isNumber || $0 == "-" }
                    let parsed = Int(digits) ?? value
                    value = min(max(parsed, range.lowerBound), range.upperBound)
                    text = ""
                },
                focused: $focused
            )
        }
    }
}

private struct DoubleControlRow: View {
    let title: String
    let suffix: String
    @Binding var value: Double
    let range: ClosedRange<Double>
    let step: Double
    let decimals: Int

    @State private var text: String = ""
    @FocusState private var focused: Bool

    var body: some View {
        HStack(spacing: 12) {
            Text(title)
            Spacer()

            let formatted = String(format: "%.\(decimals)f", value)

            EditableControlPill(
                text: Binding(
                    get: { text.isEmpty ? formatted : text },
                    set: { text = $0 }
                ),
                suffix: suffix,
                keyboard: .decimalPad,
                canDecrement: value - step >= range.lowerBound - 0.0001,
                canIncrement: value + step <= range.upperBound + 0.0001,
                decrement: { value = max(value - step, range.lowerBound) },
                increment: { value = min(value + step, range.upperBound) },
                onCommit: {
                    let cleaned = text
                        .replacingOccurrences(of: ",", with: ".")
                        .filter { $0.isNumber || $0 == "." || $0 == "-" }

                    let parsed = Double(cleaned) ?? value
                    value = min(max(parsed, range.lowerBound), range.upperBound)
                    text = ""
                },
                focused: $focused
            )
        }
    }
}

private struct TimeControlRow: View {
    let title: String
    @Binding var seconds: Int
    let range: ClosedRange<Int>
    let stepSeconds: Int

    @State private var text: String = ""
    @FocusState private var focused: Bool

    var body: some View {
        HStack(spacing: 12) {
            Text(title)
            Spacer()

            let display = formatMMSS(seconds)

            EditableControlPill(
                text: Binding(
                    get: { text.isEmpty ? display : text },
                    set: { text = $0 }
                ),
                suffix: "min",
                keyboard: .numbersAndPunctuation,
                canDecrement: seconds - stepSeconds >= range.lowerBound,
                canIncrement: seconds + stepSeconds <= range.upperBound,
                decrement: { seconds = max(seconds - stepSeconds, range.lowerBound) },
                increment: { seconds = min(seconds + stepSeconds, range.upperBound) },
                onCommit: {
                    let parsed = parseMMSS(text) ?? seconds
                    seconds = min(max(parsed, range.lowerBound), range.upperBound)
                    text = ""
                },
                focused: $focused
            )
        }
    }

    private func formatMMSS(_ totalSeconds: Int) -> String {
        let s = max(0, totalSeconds)
        let m = s / 60
        let r = s % 60
        return "\(m):" + String(format: "%02d", r)
    }

    private func parseMMSS(_ input: String) -> Int? {
        let trimmed = input.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return nil }

        if trimmed.contains(":") {
            let parts = trimmed.split(separator: ":", omittingEmptySubsequences: false)
            guard parts.count == 2 else { return nil }
            let mStr = parts[0].filter(\.isNumber)
            let sStr = parts[1].filter(\.isNumber)
            let m = Int(mStr) ?? 0
            let s = Int(sStr) ?? 0
            return max(0, m * 60 + min(s, 59))
        }

        let digits = trimmed.filter { $0.isNumber }
        return Int(digits)
    }
}

private struct EditableControlPill: View {
    @Binding var text: String
    let suffix: String?
    let keyboard: UIKeyboardType

    let canDecrement: Bool
    let canIncrement: Bool
    let decrement: () -> Void
    let increment: () -> Void

    let onCommit: () -> Void
    @FocusState.Binding var focused: Bool

    var body: some View {
        HStack(spacing: 10) {
            Button(action: decrement) {
                Image(systemName: "minus")
                    .font(.system(size: 14, weight: .semibold))
                    .frame(width: 28, height: 28)
            }
            .buttonStyle(.borderless)
            .disabled(!canDecrement)

            HStack(spacing: 6) {
                TextField("", text: $text)
                    .keyboardType(keyboard)
                    .focused($focused)
                    .multilineTextAlignment(.center)
                    .font(.system(.body, design: .rounded))
                    .monospacedDigit()
                    .frame(minWidth: 70)
                    .onSubmit { commitAndDismiss() }
                    .onChange(of: focused) { _, isFocused in
                        if !isFocused { onCommit() }
                    }

                if let suffix {
                    Text(suffix)
                        .foregroundStyle(.secondary)
                        .font(.system(.footnote, design: .rounded))
                }
            }
            .contentShape(Rectangle())
            .onTapGesture { focused = true }

            Button(action: increment) {
                Image(systemName: "plus")
                    .font(.system(size: 14, weight: .semibold))
                    .frame(width: 28, height: 28)
            }
            .buttonStyle(.borderless)
            .disabled(!canIncrement)
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 6)
        .background(.thinMaterial)
        .clipShape(Capsule())
    }

    private func commitAndDismiss() {
        onCommit()
        focused = false
    }
}
